name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: 
      - ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.12 ]

    steps:
      - uses: actions/checkout@v3

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ runner.os }}-primes
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Running server
        run: |
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py runserver & sleep 5
      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
